version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      # install dependencies first (on 1 machine)
      - cypress/install
      # now run tests
      - cypress/run:
          # give this job a custom name for clarity
          name: 'Test Setting Care Folder Output Template Backup'
          record: true 
          parallel: true 
          parallelism: 3 
          group: test 3